/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as A8f3c91e7b2d4f06IndexRouteImport } from './routes/a8f3c91e7b2d4f06/index'
import { Route as A8f3c91e7b2d4f06EstoqueRouteImport } from './routes/a8f3c91e7b2d4f06/estoque'
import { Route as ColecaoMaisVendidasRouteImport } from './routes/colecao.mais-vendidas'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as A8f3c91e7b2d4f06EstoqueIndexRouteImport } from './routes/a8f3c91e7b2d4f06/estoque/index'
import { Route as A8f3c91e7b2d4f06EstoqueIdRouteImport } from './routes/a8f3c91e7b2d4f06/estoque/$id'
import { Route as A8f3c91e7b2d4f06EstoqueNovoRouteImport } from './routes/a8f3c91e7b2d4f06/estoque/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const A8f3c91e7b2d4f06IndexRoute = A8f3c91e7b2d4f06IndexRouteImport.update({
  id: '/a8f3c91e7b2d4f06/',
  path: '/a8f3c91e7b2d4f06/',
  getParentRoute: () => rootRouteImport,
} as any)
const A8f3c91e7b2d4f06EstoqueRoute = A8f3c91e7b2d4f06EstoqueRouteImport.update({
  id: '/a8f3c91e7b2d4f06/estoque',
  path: '/a8f3c91e7b2d4f06/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoMaisVendidasRoute = ColecaoMaisVendidasRouteImport.update({
  id: '/colecao/mais-vendidas',
  path: '/colecao/mais-vendidas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const A8f3c91e7b2d4f06EstoqueIndexRoute =
  A8f3c91e7b2d4f06EstoqueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => A8f3c91e7b2d4f06EstoqueRoute,
  } as any)
const A8f3c91e7b2d4f06EstoqueIdRoute =
  A8f3c91e7b2d4f06EstoqueIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => A8f3c91e7b2d4f06EstoqueRoute,
  } as any)
const A8f3c91e7b2d4f06EstoqueNovoRoute =
  A8f3c91e7b2d4f06EstoqueNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => A8f3c91e7b2d4f06EstoqueRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/sobre': typeof SobreRoute
  '/a8f3c91e7b2d4f06/estoque': typeof A8f3c91e7b2d4f06EstoqueRouteWithChildren
  '/colecao/mais-vendidas': typeof ColecaoMaisVendidasRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/a8f3c91e7b2d4f06/': typeof A8f3c91e7b2d4f06IndexRoute
  '/a8f3c91e7b2d4f06/estoque/$id': typeof A8f3c91e7b2d4f06EstoqueIdRoute
  '/a8f3c91e7b2d4f06/estoque/novo': typeof A8f3c91e7b2d4f06EstoqueNovoRoute
  '/a8f3c91e7b2d4f06/estoque/': typeof A8f3c91e7b2d4f06EstoqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/sobre': typeof SobreRoute
  '/colecao/mais-vendidas': typeof ColecaoMaisVendidasRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/a8f3c91e7b2d4f06': typeof A8f3c91e7b2d4f06IndexRoute
  '/a8f3c91e7b2d4f06/estoque/$id': typeof A8f3c91e7b2d4f06EstoqueIdRoute
  '/a8f3c91e7b2d4f06/estoque/novo': typeof A8f3c91e7b2d4f06EstoqueNovoRoute
  '/a8f3c91e7b2d4f06/estoque': typeof A8f3c91e7b2d4f06EstoqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/sobre': typeof SobreRoute
  '/a8f3c91e7b2d4f06/estoque': typeof A8f3c91e7b2d4f06EstoqueRouteWithChildren
  '/colecao/mais-vendidas': typeof ColecaoMaisVendidasRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/a8f3c91e7b2d4f06/': typeof A8f3c91e7b2d4f06IndexRoute
  '/a8f3c91e7b2d4f06/estoque/$id': typeof A8f3c91e7b2d4f06EstoqueIdRoute
  '/a8f3c91e7b2d4f06/estoque/novo': typeof A8f3c91e7b2d4f06EstoqueNovoRoute
  '/a8f3c91e7b2d4f06/estoque/': typeof A8f3c91e7b2d4f06EstoqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/sobre'
    | '/a8f3c91e7b2d4f06/estoque'
    | '/colecao/mais-vendidas'
    | '/produto/$slug'
    | '/a8f3c91e7b2d4f06/'
    | '/a8f3c91e7b2d4f06/estoque/$id'
    | '/a8f3c91e7b2d4f06/estoque/novo'
    | '/a8f3c91e7b2d4f06/estoque/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/sobre'
    | '/colecao/mais-vendidas'
    | '/produto/$slug'
    | '/a8f3c91e7b2d4f06'
    | '/a8f3c91e7b2d4f06/estoque/$id'
    | '/a8f3c91e7b2d4f06/estoque/novo'
    | '/a8f3c91e7b2d4f06/estoque'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/sobre'
    | '/a8f3c91e7b2d4f06/estoque'
    | '/colecao/mais-vendidas'
    | '/produto/$slug'
    | '/a8f3c91e7b2d4f06/'
    | '/a8f3c91e7b2d4f06/estoque/$id'
    | '/a8f3c91e7b2d4f06/estoque/novo'
    | '/a8f3c91e7b2d4f06/estoque/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  SobreRoute: typeof SobreRoute
  A8f3c91e7b2d4f06EstoqueRoute: typeof A8f3c91e7b2d4f06EstoqueRouteWithChildren
  ColecaoMaisVendidasRoute: typeof ColecaoMaisVendidasRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  A8f3c91e7b2d4f06IndexRoute: typeof A8f3c91e7b2d4f06IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a8f3c91e7b2d4f06/': {
      id: '/a8f3c91e7b2d4f06/'
      path: '/a8f3c91e7b2d4f06'
      fullPath: '/a8f3c91e7b2d4f06/'
      preLoaderRoute: typeof A8f3c91e7b2d4f06IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a8f3c91e7b2d4f06/estoque': {
      id: '/a8f3c91e7b2d4f06/estoque'
      path: '/a8f3c91e7b2d4f06/estoque'
      fullPath: '/a8f3c91e7b2d4f06/estoque'
      preLoaderRoute: typeof A8f3c91e7b2d4f06EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/mais-vendidas': {
      id: '/colecao/mais-vendidas'
      path: '/colecao/mais-vendidas'
      fullPath: '/colecao/mais-vendidas'
      preLoaderRoute: typeof ColecaoMaisVendidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a8f3c91e7b2d4f06/estoque/': {
      id: '/a8f3c91e7b2d4f06/estoque/'
      path: '/'
      fullPath: '/a8f3c91e7b2d4f06/estoque/'
      preLoaderRoute: typeof A8f3c91e7b2d4f06EstoqueIndexRouteImport
      parentRoute: typeof A8f3c91e7b2d4f06EstoqueRoute
    }
    '/a8f3c91e7b2d4f06/estoque/$id': {
      id: '/a8f3c91e7b2d4f06/estoque/$id'
      path: '/$id'
      fullPath: '/a8f3c91e7b2d4f06/estoque/$id'
      preLoaderRoute: typeof A8f3c91e7b2d4f06EstoqueIdRouteImport
      parentRoute: typeof A8f3c91e7b2d4f06EstoqueRoute
    }
    '/a8f3c91e7b2d4f06/estoque/novo': {
      id: '/a8f3c91e7b2d4f06/estoque/novo'
      path: '/novo'
      fullPath: '/a8f3c91e7b2d4f06/estoque/novo'
      preLoaderRoute: typeof A8f3c91e7b2d4f06EstoqueNovoRouteImport
      parentRoute: typeof A8f3c91e7b2d4f06EstoqueRoute
    }
  }
}

interface A8f3c91e7b2d4f06EstoqueRouteChildren {
  A8f3c91e7b2d4f06EstoqueIdRoute: typeof A8f3c91e7b2d4f06EstoqueIdRoute
  A8f3c91e7b2d4f06EstoqueNovoRoute: typeof A8f3c91e7b2d4f06EstoqueNovoRoute
  A8f3c91e7b2d4f06EstoqueIndexRoute: typeof A8f3c91e7b2d4f06EstoqueIndexRoute
}

const A8f3c91e7b2d4f06EstoqueRouteChildren: A8f3c91e7b2d4f06EstoqueRouteChildren =
  {
    A8f3c91e7b2d4f06EstoqueIdRoute: A8f3c91e7b2d4f06EstoqueIdRoute,
    A8f3c91e7b2d4f06EstoqueNovoRoute: A8f3c91e7b2d4f06EstoqueNovoRoute,
    A8f3c91e7b2d4f06EstoqueIndexRoute: A8f3c91e7b2d4f06EstoqueIndexRoute,
  }

const A8f3c91e7b2d4f06EstoqueRouteWithChildren =
  A8f3c91e7b2d4f06EstoqueRoute._addFileChildren(
    A8f3c91e7b2d4f06EstoqueRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  SobreRoute: SobreRoute,
  A8f3c91e7b2d4f06EstoqueRoute: A8f3c91e7b2d4f06EstoqueRouteWithChildren,
  ColecaoMaisVendidasRoute: ColecaoMaisVendidasRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  A8f3c91e7b2d4f06IndexRoute: A8f3c91e7b2d4f06IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
